# Generated by Django 5.0.2 on 2025-03-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Obraz wyróżniający dla posta', null=True, upload_to='blog_images/'),
        ),
    ]
